name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci && npm run bootstrap:ci

#    - name: Lint
#      run: npm run lint

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build && npm run app:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
