name: Deploy To Cloud

on:
  push:
    branches:
      - master
    paths:
      - 'packages/cloud-containers/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            ref: master
            fetch-depth: 2

      - uses: google-github-actions/setup-gcloud@master
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID_CLOUD }}
            service_account_key: ${{ secrets.GCP_SA_KEY_CLOUD }}
            export_default_credentials: true

      - name: Check Google Cloud
        run: gcloud info && gcloud auth configure-docker -q

      - name: Reset to master
        run: git checkout master && git reset --hard

      - name: Build & Push Changed Cloud Images
        run: npm run build_push_cloud

      - name: Get latest Terraform start
        run: gsutil cp gs://artifacts.crystallography.io/terraform.tfstate terraform.tfstate

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_MONGO_CONNECTION: ${{ secrets.MONGO_CONNECTION }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_MONGO_CONNECTION: ${{ secrets.MONGO_CONNECTION }}

      - name: Store new cluster state
        run: gsutil cp ./terraform.tfstate gs://artifacts.crystallography.io/terraform.tfstate
