name: Release Application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # List of platforms
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    # Build Steps
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1.0.0
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci && npm run bootstrap:ci

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        with:
          # Log in to Snap Store
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          package_root: 'packages/application/structure-search'
          build_script_name: 'app:build:js'

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
