name: Deploy Swarm

on:
  push:
    branches:
      - master
    paths:
      - 'packages/containers/**'


jobs: # Jobs List
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            ref: master
            fetch-depth: 2

      - name: 'Setup auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          version: '300.0.0'
        env:
          CLOUDSDK_PYTHON: python2

      - name: Check Google Cloud
        run: gcloud info && gcloud auth configure-docker -q

      - name: Install dependencies
        run: npm ci && npm run bootstrap:ci

      - name: Reset to master
        run: git checkout master && git reset --hard

      - name: Build Images
        run: docker-compose -f docker-compose.yaml build

      - name: Push Images
        run: docker-compose -f docker-compose.yaml  push

      - name: Build & Push Changed Images
        run: npm run build_push

      - name: Deploy to Docker swarm
        uses: vreshch/docker-deployment-action@master
        with:
            remote_docker_host: root@host.crystallography.io
            ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
            ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
            pre_deployment_step_command: docker image prune && /root/google-cloud-sdk/bin/gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            deployment_mode: docker-swarm
            copy_stack_file: true
            pull_images_first: true
            deploy_path: /root
            stack_file_name: docker-compose.yaml
            keep_files: 5
            args: --resolve-image=always --with-registry-auth crystallography-io
